// app/lib/sponsors.ts
const sponsorsList = [
    { id: 1, name: 'Argennova', src: '/sponsor/argennova.jpg', url: 'https://argennova.org/' },
    { id: 2, name: 'Argennova 2', src: '/sponsor/argennova2.jpg', url: 'https://argennova.org/' },
    { id: 3, name: 'Argennova Oficial', src: '/sponsor/argennovaoficial.jpg', url: 'https://argennova.org/' },
    { id: 4, name: 'Berisys', src: '/sponsor/berisys.jpg', url: 'https://crm.berisys.com.ar/' },
    { id: 5, name: 'Berisys 2', src: '/sponsor/berisys2.jpg', url: 'https://crm.berisys.com.ar/' },
    { id: 6, name: 'Be The Drive', src: '/sponsor/bethedrive.jpg', url: 'https://bethedriver.global/' },
    { id: 7, name: 'Be The Drive 2', src: '/sponsor/bethedrive2.jpg', url: 'https://bethedriver.global/' },
    { id: 8, name: 'Bisenergia', src: '/sponsor/bisenergia.jpg', url: 'https://www.bisenergia.com/' },
    { id: 9, name: 'Bolsas Ecologicas', src: '/sponsor/bolsasecologicas.jpg', url: 'https://www.bolsasecologicas.com.ar/' },
    { id: 10, name: 'Bolsas Ecologicas 2', src: '/sponsor/bolsasecologicas2.jpg', url: 'https://www.bolsasecologicas.com.ar/' },
    { id: 11, name: 'Dag', src: '/sponsor/dag.jpg', url: 'https://www.resortesdag.com.ar/' },
    { id: 12, name: 'Ecoenergia', src: '/sponsor/ecoenergia.jpg', url: 'https://eco-energia.com.ar/' },
    { id: 13, name: 'Ecotec', src: '/sponsor/ecotec.jpg', url: 'https://ecotecalternativas.wixsite.com/coop' },
    { id: 14, name: 'Fagus', src: '/sponsor/fagus.jpg', url: 'https://www.tiendafagua.com.ar/' },
    { id: 15, name: 'Gestion Parque', src: '/sponsor/gestionparque.jpg', url: 'https://gestionparque.com.ar/' },
    { id: 16, name: 'JLF', src: '/sponsor/jlf.jpg', url: 'https://electrojlf.com.ar/' },
    { id: 17, name: 'JLF 2', src: '/sponsor/jlf2.jpg', url: 'https://electrojlf.com.ar/' },
    { id: 18, name: 'MC Cordones', src: '/sponsor/mccordones.jpg', url: 'https://mccordones.com.ar/' },
    { id: 19, name: 'Metsur', src: '/sponsor/metsur.jpg', url: 'https://metsur.com/' },
    { id: 20, name: 'Nitti Hermanos', src: '/sponsor/nittihermanos.jpg', url: '#https://nittihnosautopartes.mercadoshops.com.ar/' },
    { id: 21, name: 'Pallet Pro', src: '/sponsor/palletpro.jpg', url: 'https://palletpro.com.ar/' },
    { id: 22, name: 'Pallet Pro 2', src: '/sponsor/palletpro2.jpg', url: 'https://palletpro.com.ar/' },
    { id: 23, name: 'RDS', src: '/sponsor/rds.jpg', url: 'https://www.instagram.com/reparaciones.del.sur/' },
    { id: 24, name: 'RDS 2', src: '/sponsor/rds2.jpg', url: 'https://www.instagram.com/reparaciones.del.sur/' },
    { id: 25, name: 'RF Soluciones', src: '/sponsor/rfsoluciones.jpg', url: '#' },
    { id: 26, name: 'RF Soluciones 2', src: '/sponsor/rfsoluciones2.jpg', url: '#' },
    { id: 27, name: 'Santa Cruz', src: '/sponsor/santacruz.jpg', url: 'https://alimentossantacruz.com/' },
    { id: 28, name: 'Santa Cruz 2', src: '/sponsor/santacruz2.jpg', url: 'https://alimentossantacruz.com/' },
    { id: 29, name: 'Selsa', src: '/sponsor/selsa.jpg', url: 'https://selsa.com.ar/' },
    { id: 30, name: 'Selsa2', src: '/sponsor/selsa2.jpg', url: 'https://selsa.com.ar/' },
    { id: 31, name: 'Selsa Oficial', src: '/sponsor/selsaoficial.jpg', url: 'https://selsa.com.ar/' },
    { id: 32, name: 'Sergio Gerullo', src: '/sponsor/sergiogerullo.jpg', url: 'https://www.sergiocerullo.com.ar/' },
    { id: 33, name: 'Shekk', src: '/sponsor/shekk.jpg', url: 'https://find.shell.com/ar/fuel/10130005-kosc-nicolas-s-a/es_AR' },
    { id: 34, name: 'Smartway', src: '/sponsor/smartway.jpg', url: 'https://www.smartway.com.ar/' },
    { id: 35, name: 'Solari', src: '/sponsor/solari.jpg', url: 'https://ejsolari.com/' },
    { id: 36, name: 'Solari 2', src: '/sponsor/solari2.jpg', url: 'https://ejsolari.com/' },
    { id: 37, name: 'Starting Point', src: '/sponsor/startingpoint.jpg', url: 'https://www.startingpoint.com.ar/' },
    { id: 38, name: 'Todos los Sponsor', src: '/sponsor/todoslossponsor.jpg', url: '#' },
    { id: 39, name: 'Torcel', src: '/sponsor/torcel.jpg', url: 'https://torcel.com.ar/' },
    { id: 40, name: 'Trabajamos', src: '/sponsor/trabajamos.jpg', url: '#' },
    { id: 41, name: 'Work', src: '/sponsor/work.jpg', url: 'https://estabilizadoreswork.com.ar/' },
  ];
  
  export default sponsorsList;
  