// app/lib/sponsors.ts
const sponsorsList = [
    { id: 1, name: 'Argennova', image: '/sponsor/argennova.jpg', url: '#' },
    { id: 2, name: 'Argennova 2', image: '/sponsor/argennova2.jpg', url: '#' },
    { id: 3, name: 'Argennova Oficial', image: '/sponsor/argennovaoficial.jpg', url: '#' },
    { id: 4, name: 'Berisys', image: '/sponsor/berisys.jpg', url: '#' },
    { id: 5, name: 'Berisys 2', image: '/sponsor/berisys2.jpg', url: '#' },
    { id: 6, name: 'Be The Drive', image: '/sponsor/bethedrive.jpg', url: '#' },
    { id: 7, name: 'Be The Drive 2', image: '/sponsor/bethedrive2.jpg', url: '#' },
    { id: 8, name: 'Bisenergia', image: '/sponsor/bisenergia.jpg', url: '#' },
    { id: 9, name: 'Bolsas Ecologicas', image: '/sponsor/bolsasecologicas.jpg', url: '#' },
    { id: 10, name: 'Bolsas Ecologicas 2', image: '/sponsor/bolsasecologicas2.jpg', url: '#' },
    { id: 11, name: 'Dag', image: '/sponsor/dag.jpg', url: '#' },
    { id: 12, name: 'Ecoenergia', image: '/sponsor/ecoenergia.jpg', url: '#' },
    { id: 13, name: 'Ecotec', image: '/sponsor/ecotec.jpg', url: '#' },
    { id: 14, name: 'Fagus', image: '/sponsor/fagus.jpg', url: '#' },
    { id: 15, name: 'Gestion Parque', image: '/sponsor/gestionparque.jpg', url: '#' },
    { id: 16, name: 'JLF', image: '/sponsor/jlf.jpg', url: '#' },
    { id: 17, name: 'JLF 2', image: '/sponsor/jlf2.jpg', url: '#' },
    { id: 18, name: 'MC Cordones', image: '/sponsor/mccordones.jpg', url: '#' },
    { id: 19, name: 'Metsur', image: '/sponsor/metsur.jpg', url: '#' },
    { id: 20, name: 'Nitti Hermanos', image: '/sponsor/nittihermanos.jpg', url: '#' },
    { id: 21, name: 'Pallet Pro', image: '/sponsor/palletpro.jpg', url: '#' },
    { id: 22, name: 'Pallet Pro 2', image: '/sponsor/palletpro2.jpg', url: '#' },
    { id: 23, name: 'RDS', image: '/sponsor/rds.jpg', url: '#' },
    { id: 24, name: 'RDS 2', image: '/sponsor/rds2.jpg', url: '#' },
    { id: 25, name: 'RF Soluciones', image: '/sponsor/rfsoluciones.jpg', url: '#' },
    { id: 26, name: 'RF Soluciones 2', image: '/sponsor/rfsoluciones2.jpg', url: '#' },
    { id: 27, name: 'Santa Cruz', image: '/sponsor/santacruz.jpg', url: '#' },
    { id: 28, name: 'Santa Cruz 2', image: '/sponsor/santacruz2.jpg', url: '#' },
    { id: 29, name: 'Selsa', image: '/sponsor/selsa.jpg', url: '#' },
    { id: 30, name: 'Selsa2', image: '/sponsor/selsa2.jpg', url: '#' },
    { id: 31, name: 'Selsa Oficial', image: '/sponsor/selsaoficial.jpg', url: '#' },
    { id: 32, name: 'Sergio Gerullo', image: '/sponsor/sergiogerullo.jpg', url: '#' },
    { id: 33, name: 'Shekk', image: '/sponsor/shekk.jpg', url: '#' },
    { id: 34, name: 'Smartway', image: '/sponsor/smartway.jpg', url: '#' },
    { id: 35, name: 'Solari', image: '/sponsor/solari.jpg', url: '#' },
    { id: 36, name: 'Solari 2', image: '/sponsor/solari2.jpg', url: '#' },
    { id: 37, name: 'Starting Point', image: '/sponsor/startingpoint.jpg', url: '#' },
    { id: 38, name: 'Todos los Sponsor', image: '/sponsor/todoslossponsor.jpg', url: '#' },
    { id: 39, name: 'Torcel', image: '/sponsor/torcel.jpg', url: '#' },
    { id: 40, name: 'Trabajamos', image: '/sponsor/trabajamos.jpg', url: '#' },
    { id: 41, name: 'Work', image: '/sponsor/work.jpg', url: '#' },
  ];
  
  export default sponsorsList;
  