{/* COMPONENTE NUEVO */}
           <aside className="order-3 lg:order-2 hidden md:block lg:col-span-1 my-1">
            <SidenavComplement
            className="hidden md:block"
              socialLinks={[
                { type: "facebook", href: "https://www.facebook.com", label: "Facebook" },
                { type: "twitter", href: "https://twitter.com", label: "Twitter" },
                { type: "instagram", href: "https://instagram.com", label: "Instagram" },
                { type: "email", href: "mailto:info@radioempresarial.com", label: "Email" },
              ]}
              sponsors={[
                { image: "/sponsor/argennova.jpg", alt: "Argennova", href: "#" },
                { image: "/sponsor/argennova2.jpg", alt: "Argennova2", href: "#" },
                { image: "/sponsor/argennovaoficial.jpg", alt: "Argennovaoficial", href: "#" },
                { image: "/sponsor/berisys.jpg", alt: "Berisys", href: "#" },
                { image: "/sponsor/berisys2.jpg", alt: "Berisys2", href: "#" },
                { image: "/sponsor/bethedrive.jpg", alt: "Bethedrive", href: "#" },
                { image: "/sponsor/bethedrive2.jpg", alt: "Bethedrive2", href: "#" },
                { image: "/sponsor/bisenergia.jpg", alt: "Bisenergia", href: "#" },
                { image: "/sponsor/bolsasecologicas.jpg", alt: "Bolsasecologicas", href: "#" },
                { image: "/sponsor/bolsasecologicas2.jpg", alt: "Bolsasecologicas2", href: "#" },
                { image: "/sponsor/dag.jpg", alt: "Dag", href: "#" },
                { image: "/sponsor/ecoenergia.jpg", alt: "Ecoenergia", href: "#" },
                { image: "/sponsor/ecotec.jpg", alt: "Ecotec", href: "#" },
                { image: "/sponsor/fagus.jpg", alt: "Fagus", href: "#" },
                { image: "/sponsor/gestionparque.jpg", alt: "Gestionparque", href: "#" },
                { image: "/sponsor/jlf.jpg", alt: "Jlf", href: "#" },
                { image: "/sponsor/jlf2.jpg", alt: "Jlf2", href: "#" },
                { image: "/sponsor/mccordones.jpg", alt: "Mccordones", href: "#" },
                { image: "/sponsor/metsur.jpg", alt: "Metsur", href: "#" },
                { image: "/sponsor/nittihermanos.jpg", alt: "Nittihermanos", href: "#" },
                { image: "/sponsor/palletpro.jpg", alt: "Palletpro", href: "#" },
                { image: "/sponsor/palletpro2.jpg", alt: "Palletpro2", href: "#" },
                { image: "/sponsor/rds.jpg", alt: "Rds", href: "#" },
                { image: "/sponsor/rds2.jpg", alt: "Rds2", href: "#" },
                { image: "/sponsor/rfsoluciones.jpg", alt: "Rfsoluciones", href: "#" },
                { image: "/sponsor/rfsoluciones2.jpg", alt: "Rfsoluciones2", href: "#" },
                { image: "/sponsor/santacruz.jpg", alt: "Santacruz", href: "#" },
                { image: "/sponsor/santacruz2.jpg", alt: "Santacruz2", href: "#" },
                { image: "/sponsor/selsa.jpg", alt: "Selsa", href: "#" },
                { image: "/sponsor/selsa2.jpg", alt: "Selsa2", href: "#" },
                { image: "/sponsor/selsaoficial.jpg", alt: "Selsaoficial", href: "#" },
                { image: "/sponsor/sergiogerullo.jpg", alt: "Sergiogerullo", href: "#" },
                { image: "/sponsor/shekk.jpg", alt: "Shekk", href: "#" },
                { image: "/sponsor/smartway.jpg", alt: "Smartway", href: "#" },
                { image: "/sponsor/solari.jpg", alt: "Solari", href: "#" },
                { image: "/sponsor/solari2.jpg", alt: "Solari2", href: "#" },
                { image: "/sponsor/startingpoint.jpg", alt: "Startingpoint", href: "#" },
                { image: "/sponsor/todoslossponsor.jpg", alt: "Todoslossponsor", href: "#" },
                { image: "/sponsor/torcel.jpg", alt: "Torcel", href: "#" },
                { image: "/sponsor/trabajamos.jpg", alt: "Trabajamos", href: "#" },
                { image: "/sponsor/work.jpg", alt: "Work", href: "#" },
              ]}
            />
          </aside>